"""new fields in user model

Revision ID: 551eaf2bb1f3
Revises: ca06fa606411
Create Date: 2020-04-01 18:57:45.661762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551eaf2bb1f3'
down_revision = 'ca06fa606411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
